cleanup: Added Bold & Italic support for articles
Vanilla-OS/website pull request #142
Opened 2023-11-19 14:57 UTC by GabsEdits

To allow `**.**` and `*.*` in articles and be showen

2023-11-19 15:13 UTC, kbdharun approved these changes

2023-11-19 18:47 UTC, kbdharun approved these changes
Tested the changes with the recent articles LGTM.

Ref (deployment). https://b7aa09be.gabs.pages.dev/

## Sample Images

Before

![image](https://github.com/Vanilla-OS/website/assets/26346867/aa46c3c2-a0b3-4eaa-a596-01699a978bcd)


After

![image](https://github.com/Vanilla-OS/website/assets/26346867/6c36b51b-eadd-4133-9295-8393ce4fb564)

2023-11-22 21:33 UTC, mirkobrombin commented
Articles uses the `.text--rich` class to allow formatting https://github.com/Vanilla-OS/website/blob/b92b2c55f5d6ae25ccec43c7ba4ca93549234c2d/src/views/Article.vue#L15C29-L15C40
Bold and other formats should be added in that context rather than in the common stylesheet, this is because every component could handle the formatting its own way.

2023-11-22 21:33 UTC, mirkobrombin requested changes
Articles uses the `.text--rich` class to allow formatting https://github.com/Vanilla-OS/website/blob/b92b2c55f5d6ae25ccec43c7ba4ca93549234c2d/src/views/Article.vue#L15C29-L15C40
Bold and other formats should be added in that context rather than in the common stylesheet, this is because every component could handle the formatting its own way.

2023-11-24 21:23 UTC, mirkobrombin approved these changes

2023-11-24 21:24 UTC, merged